### PR TITLE
Implementing more models via langchain

### PR DESCRIPTION
**Pull request by hrshdhgd**
- [x] ollama: `llama3.1`
- [x] anthropic: `claude-3-5-sonnet-20240620`
- [ ] Investigating how to implement CBORG [[in next PR]](https://github.com/Knowledge-Graph-Hub/kg-chat/pull/8)

### CODE REVIEW

**Comment by justaddcoffee** [comment]
Seems to work on my end 

Two few possible improvements:

- shouldn't the `--llm` refer to the model, and not the provider? I think for example now you have to do this:
`kg qna "How many unique nodes are in the database?"  --data-dir data/ --llm anthropic`
but should this maybe be:
`kg qna "How many unique nodes are in the database?"  --data-dir data/ --llm claude-3-5-sonnet`
since Anthropic has a bunch of different models that users might want to use

- could add something in the README to help users to set API keys correctly. I think they have to do this to use Anthropic models:

  `ANTHROPIC_API_KEY="users anthropic key" kg qna "How many unique nodes are in the database?" --llm anthropic`

  and this to use OpenAI models:
  
  `OPENAI_API_KEY="users OpenAI key" kg qna "How many unique nodes are in the database?"`

  As it is, I think users have to figure this out themselves (which to be fair isn't too hard, but still)

**Review by justaddcoffee — COMMENTED** [review]
see comment above for some suggestions

**Comment by hrshdhgd** [comment]
>shouldn't the --llm refer to the model, and not the provider? I think for example now you have to do this:
kg qna "How many unique nodes are in the database?"  --data-dir data/ --llm anthropic
but should this maybe be:
kg qna "How many unique nodes are in the database?"  --data-dir data/ --llm claude-3-5-sonnet
since Anthropic has a bunch of different models that users might want to use

I thought of it and am glad you brought it up. I did that since not all models from `Ollama` will work for us. Only the ones that support tool calling would work. So we basically control the exact model to use. By mentioning the providers as parameters there are just 3 choices to choose from. This way we don't let the user "figure it out" in terms of which model work and which don't. I could switch it to the actual model name if you strongly feel so. Just wanted another opinion about this.


>could add something in the README to help users to set API keys correctly. I think they have to do this to use Anthropic models:
ANTHROPIC_API_KEY="users anthropic key" kg qna "How many unique nodes are in the database?" --llm anthropic
and this to use OpenAI models:
OPENAI_API_KEY="users OpenAI key" kg qna "How many unique nodes are in the database?"
As it is, I think users have to figure this out themselves (which to be fair isn't too hard, but still)

I can do that.

**Comment by caufieldjh** [comment]
Copy the error I saw here:
```bash
~/kg-chat$ kg qna "How many unique nodes are in the database?"  --data-dir data/ --llm ollama
/home/harry/kg-chat/.venv/lib/python3.10/site-packages/duckdb_engine/__init__.py:579: SAWarning: Did not recognize type 'list' of column 'constraint_column_indexes'
  columns = self._get_columns_info(rows, domains, enums, schema)  # type: ignore[attr-defined]
/home/harry/kg-chat/.venv/lib/python3.10/site-packages/duckdb_engine/__init__.py:579: SAWarning: Did not recognize type 'list' of column 'constraint_column_names'
  columns = self._get_columns_info(rows, domains, enums, schema)  # type: ignore[attr-defined]
/home/harry/kg-chat/.venv/lib/python3.10/site-packages/duckdb_engine/__init__.py:579: SAWarning: Did not recognize type 'map' of column 'tags'
  columns = self._get_columns_info(rows, domains, enums, schema)  # type: ignore[attr-defined]
/home/harry/kg-chat/.venv/lib/python3.10/site-packages/duckdb_engine/__init__.py:579: SAWarning: Did not recognize type 'list' of column 'labels'
  columns = self._get_columns_info(rows, domains, enums, schema)  # type: ignore[attr-defined]
/home/harry/kg-chat/.venv/lib/python3.10/site-packages/duckdb_engine/__init__.py:173: DuckDBEngineWarning: duckdb-engine doesn't yet support reflection on indices
  warnings.warn(


> Entering new SQL Agent Executor chain...


Action: sql_db_list_tables
Action Input:Traceback (most recent call last):
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 1370, in _iter_next_step
    output = self.agent.plan(
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 463, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3253, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3240, in transform
    yield from self._transform_stream_with_config(
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2053, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3202, in _transform
    for output in final_pipeline:
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1289, in transform
    yield from self.stream(final, config, **kwargs)
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 854, in stream
    yield self.invoke(input, config, **kwargs)
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 183, in invoke
    return self._call_with_config(
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1784, in _call_with_config
    context.run(
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 404, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 184, in <lambda>
    lambda inner_input: self.parse_result(
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 237, in parse_result
    return self.parse(result[0].text)
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain/agents/output_parsers/react_single_input.py", line 75, in parse
    raise OutputParserException(
langchain_core.exceptions.OutputParserException: Could not parse LLM output: ``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harry/kg-chat/.venv/bin/kg", line 6, in <module>
    sys.exit(main())
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/kg-chat/src/kg_chat/cli.py", line 111, in qna
    response = impl.get_human_response(query)
  File "/home/harry/kg-chat/src/kg_chat/implementations/duckdb_implementation.py", line 74, in get_human_response
    response = self.agent.invoke(prompt)
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain/chains/base.py", line 166, in invoke
    raise e
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 1636, in _call
    next_step_output = self._take_next_step(
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 1342, in _take_next_step
    [
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 1342, in <listcomp>
    [
  File "/home/harry/kg-chat/.venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 1381, in _iter_next_step
    raise ValueError(
ValueError: An output parsing error occurred. In order to pass this error back to the agent and have it try again, pass `handle_parsing_errors=True` to the AgentExecutor. This is the error: Could not parse LLM output: ``
```

**Comment by caufieldjh** [comment]
Still seeing that error after re-installing from scratch and creating a fresh db.

**Pull request merged**
